import Header from "@/components/Layout/Header";
import type { Metadata } from "next";

// import Footer from "@/components/Layout/Footer";

export const metadata: Metadata = {
  title: "DevNest",
  description: "Generated by create next app",
};

export default function layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      {children}
      {/* <Footer /> */}
    </>
  );
}
