import Footer from "@/components/Layout/Footer";
import Header from "@/components/Layout/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "DevNest | Blog",
  description: "Generated by create next app",
};

export default function layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
}
